# -*- coding: utf-8 -*-
"""scene_segmentation_train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/abhinav0231/scene-segmentation-train.e85c0fea-394a-4f89-a8f9-1d3371931cc2.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260131/auto/storage/goog4_request%26X-Goog-Date%3D20260131T143007Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D3918e66096bd33b7d7496f5e68b3ae5fc988d9077a9a274913cd300786bcdfd4bc06b9380dbdb74200cf22f5234f6cd45cd92fb9a0b9fa13dc1e2f48da2ee67ce0db53e90fb38fb96d6a679d2abcbdcf0cd529439135aadbad7b34115cf7c71065fcf50aeba1c884b32cd979bf176bccd13bdf04ce88f4807a550b262264d98446171b3acf5c173e3d8ecbb1771175b079d7eea73e15182262c027e09f510c65543f884d533a8404b4d337e3e8cf2cd3cbc24d7ea87566c04ee833c5236ac679bf36545da4579f732566dc3a44d87642c1f2195a52a35d147d8cb496be681d3cb04732629a4474df1822cf7420b63a066fa1006e2aaab81bdf1ebd58188108d8
"""

!pip install -q gdown

import gdown

file_id = "15p1d523C0Zyocnug53HrLWtAZ8XV_kTU"
output = "/kaggle/working/data.zip"

gdown.download(id=file_id, output=output, quiet=False)

!unzip -q /kaggle/working/data.zip -d /kaggle/working/data

import gdown

file_id = "12dNsuo452p7BJN9SjItWJCJtZDCOldHe"
output = "/kaggle/working/extra.zip"

gdown.download(id=file_id, output=output, quiet=False)

!unzip -o /kaggle/working/extra.zip \
-d /kaggle/working/data/Offroad_Segmentation_Training_Dataset

!pip install -q segmentation-models-pytorch albumentations

!pip install -U wandb

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import segmentation_models_pytorch as smp
import albumentations as A
from albumentations.pytorch import ToTensorV2
from collections import Counter
import cv2
import numpy as np
from pathlib import Path
from tqdm import tqdm
import matplotlib.pyplot as plt
import wandb
import json
from datetime import datetime
import shutil
import time

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"Device: {'cuda' if torch.cuda.is_available() else 'cpu'}")

class Config:
    # Project info
    PROJECT_NAME = "duality-offroad-segmentation"
    RUN_NAME = f"unet-resnet34-multi-gpu-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    # Kaggle paths
    DATA_ROOT = "/kaggle/input/offroad-segmentation-dataset"
    DATASET_ROOT = "/kaggle/working/data/Offroad_Segmentation_Training_Dataset"
    CHECKPOINT_DIR = f"/kaggle/working/checkpoints/{RUN_NAME}"
    OUTPUT_DIR = f"/kaggle/working/outputs/{RUN_NAME}"

    # Dataset paths
    TRAIN_IMG_DIR = f"{DATASET_ROOT}/train/Color_Images"
    TRAIN_MASK_DIR = f"{DATASET_ROOT}/train/Segmentation"
    VAL_IMG_DIR = f"{DATASET_ROOT}/val/Color_Images"
    VAL_MASK_DIR = f"{DATASET_ROOT}/val/Segmentation"
    TEST_IMG_DIR = f"/kaggle/working/data/Offroad_Segmentation_Training_Dataset/test"

    # Model
    ENCODER = "resnet34"
    ENCODER_WEIGHTS = "imagenet"
    NUM_CLASSES = 10
    ACTIVATION = None

    # Training - Multi-GPU optimized
    USE_MULTI_GPU = True
    USE_AMP = True
    BATCH_SIZE = 16
    NUM_EPOCHS = 100
    LEARNING_RATE = 5e-4
    WEIGHT_DECAY = 1e-4
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    NUM_WORKERS = 4

    # Image
    IMG_HEIGHT = 544
    IMG_WIDTH = 960

    # Class mapping
    CLASS_MAPPING = {
        100: 0,    # Trees
        200: 1,    # Lush Bushes
        300: 2,    # Dry Grass
        500: 3,    # Dry Bushes
        550: 4,    # Ground Clutter
        600: 5,    # Flowers
        700: 6,    # Logs
        800: 7,    # Rocks
        7100: 8,   # Landscape
        10000: 9,  # Sky
    }

    CLASS_NAMES = ["Trees", "Lush Bushes", "Dry Grass", "Dry Bushes",
                   "Ground Clutter", "Flowers", "Logs", "Rocks",
                   "Landscape", "Sky"]

    # Early stopping
    EARLY_STOPPING_PATIENCE = 20
    MIN_DELTA = 0.001

    # Checkpointing
    SAVE_FREQUENCY = 5           # Save checkpoint every N epochs
    KEEP_LAST_N_CHECKPOINTS = 3  # Keep last 3 .pth files
    BACKUP_FREQUENCY = 5         # Create full ZIP every N epochs

    # Resume training
    RESUME_FROM_CHECKPOINT = None

    # WandB
    USE_WANDB = True

# Create directories
Path(Config.CHECKPOINT_DIR).mkdir(parents=True, exist_ok=True)
Path(Config.OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

print("=" * 70)
print("✓ Configuration loaded")
print(f"✓ Run name: {Config.RUN_NAME}")
print(f"✓ Checkpoints: {Config.CHECKPOINT_DIR}")
print(f"✓ ZIP backup every {Config.BACKUP_FREQUENCY} epochs")
print(f"✓ Keeps last 2 full ZIPs + last 2 quick ZIPs")
print("=" * 70)

# CELL 4: WandB Initialization
if Config.USE_WANDB:
    try:
        # Go to Kaggle notebook settings → Add-ons → Secrets
        # Add a secret with name 'WANDB_API_KEY' and your WandB API key as value
        from kaggle_secrets import UserSecretsClient
        user_secrets = UserSecretsClient()
        wandb_api_key = user_secrets.get_secret("WANDB_API_KEY")

        import os
        os.environ['WANDB_API_KEY'] = wandb_api_key
        wandb.login(key=wandb_api_key)

        wandb.init(
            project=Config.PROJECT_NAME,
            name=Config.RUN_NAME,
            config={
                "encoder": Config.ENCODER,
                "batch_size": Config.BATCH_SIZE,
                "learning_rate": Config.LEARNING_RATE,
                "epochs": Config.NUM_EPOCHS,
                "image_size": f"{Config.IMG_HEIGHT}x{Config.IMG_WIDTH}",
                "multi_gpu": Config.USE_MULTI_GPU,
                "mixed_precision": Config.USE_AMP,
                "num_gpus": torch.cuda.device_count(),
            }
        )
        print("✓ WandB initialized successfully")

    except Exception as e:
        print(f"⚠ WandB initialization failed: {e}")
        print("Continuing without WandB logging...")
        Config.USE_WANDB = False
else:
    print("WandB disabled")

def get_training_augmentation():
    """Comprehensive on-the-fly augmentations"""
    return A.Compose([
        A.RandomRotate90(p=0.5),
        A.HorizontalFlip(p=0.5),
        A.VerticalFlip(p=0.2),
        A.ShiftScaleRotate(
            shift_limit=0.1,
            scale_limit=0.2,
            rotate_limit=30,
            border_mode=cv2.BORDER_CONSTANT,
            p=0.5,
        ),
        A.RandomResizedCrop(
            size=(Config.IMG_HEIGHT, Config.IMG_WIDTH),
            scale=(0.7, 1.0),
            p=0.5,
        ),
        A.RandomBrightnessContrast(
            brightness_limit=0.3,
            contrast_limit=0.3,
            p=0.7,
        ),
        A.RandomGamma(gamma_limit=(80, 120), p=0.5),
        A.HueSaturationValue(
            hue_shift_limit=20,
            sat_shift_limit=30,
            val_shift_limit=20,
            p=0.5,
        ),
        A.OneOf([
            A.RandomSunFlare(p=1),
            A.RandomShadow(p=1),
            A.RandomFog(p=1),
        ], p=0.3),
        A.OneOf([
            A.MotionBlur(blur_limit=5, p=1),
            A.MedianBlur(blur_limit=5, p=1),
            A.GaussianBlur(blur_limit=5, p=1),
        ], p=0.3),
        A.OneOf([
            A.GaussNoise(p=1),
            A.ISONoise(p=1),
        ], p=0.3),
        A.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1, p=0.5),
        A.CoarseDropout(p=0.3),

        # Always resize to target size at the end
        A.Resize(Config.IMG_HEIGHT, Config.IMG_WIDTH),

        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ])

def get_validation_augmentation():
    """Minimal augmentation for validation"""
    return A.Compose([
        A.Resize(Config.IMG_HEIGHT, Config.IMG_WIDTH),
        A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
        ToTensorV2(),
    ])

print("Augmentation functions defined")

class DesertSegmentationDataset(Dataset):
    """Dataset for Duality AI Challenge"""
    def __init__(self, image_dir, mask_dir, transform=None):
        self.image_dir = Path(image_dir)
        self.mask_dir = Path(mask_dir)
        self.transform = transform

        # Get image paths
        self.image_paths = sorted(list(self.image_dir.glob("*.png")))
        if len(self.image_paths) == 0:
            self.image_paths = sorted(list(self.image_dir.glob("*.jpg")))

        print(f"Found {len(self.image_paths)} images in {image_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        # Load image
        img_path = self.image_paths[idx]
        image = cv2.imread(str(img_path))
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Load mask
        mask_path = self.mask_dir / img_path.name
        mask = cv2.imread(str(mask_path), cv2.IMREAD_UNCHANGED)

        if mask is None:
            raise FileNotFoundError(f"Mask not found: {mask_path}")

        # Remap mask
        remapped_mask = np.zeros_like(mask, dtype=np.int64)
        for old_id, new_id in Config.CLASS_MAPPING.items():
            remapped_mask[mask == old_id] = new_id

        # Apply augmentations
        if self.transform:
            augmented = self.transform(image=image, mask=remapped_mask)
            image = augmented['image']
            remapped_mask = augmented['mask']

        return image, remapped_mask.long()

print("Dataset class defined")

from collections import Counter

def check_class_distribution(mask_dir, dataset_name="Dataset"):
    """Check pixel-wise class distribution"""
    class_counts = Counter()
    image_class_presence = {i: 0 for i in range(Config.NUM_CLASSES)}

    mask_paths = list(Path(mask_dir).glob("*.png"))
    if len(mask_paths) == 0:
        mask_paths = list(Path(mask_dir).glob("*.jpg"))

    print(f"\n{dataset_name} - Total images: {len(mask_paths)}")

    for mask_path in tqdm(mask_paths, desc=f"Analyzing {dataset_name}"):
        mask = cv2.imread(str(mask_path), cv2.IMREAD_UNCHANGED)

        # Remap mask
        remapped_mask = np.zeros_like(mask, dtype=np.int64)
        for old_id, new_id in Config.CLASS_MAPPING.items():
            remapped_mask[mask == old_id] = new_id

        # Count pixels
        unique, counts = np.unique(remapped_mask, return_counts=True)
        for cls, count in zip(unique, counts):
            class_counts[cls] += count
            image_class_presence[cls] += 1

    # Print results
    total_pixels = sum(class_counts.values())
    print(f"\n{dataset_name} Class Distribution:")
    print("-" * 70)
    for i, class_name in enumerate(Config.CLASS_NAMES):
        pixel_count = class_counts.get(i, 0)
        pixel_pct = (pixel_count / total_pixels * 100) if total_pixels > 0 else 0
        img_presence = image_class_presence.get(i, 0)
        img_pct = (img_presence / len(mask_paths) * 100) if len(mask_paths) > 0 else 0
        print(f"{class_name:15s}: {pixel_count:12,d} pixels ({pixel_pct:5.2f}%) | "
              f"Present in {img_presence:4d}/{len(mask_paths)} images ({img_pct:5.2f}%)")

    return class_counts, image_class_presence

# Check distributions
print("=" * 70)
print("ANALYZING CLASS DISTRIBUTIONS")
print("=" * 70)

train_dist, train_presence = check_class_distribution(Config.TRAIN_MASK_DIR, "TRAIN")
val_dist, val_presence = check_class_distribution(Config.VAL_MASK_DIR, "VAL")

total_pixels = sum(train_dist.values())

# Manual weights with strategic boosting
class_weights = torch.tensor([
    1.1,   # Trees (good at 0.69)
    0.9,   # Lush Bushes (good at 0.67)
    0.6,   # Dry Grass (good at 0.67, most common)
    3.0,   # Dry Bushes ← BOOSTED from 1.59 to 3.0
    1.2,   # Ground Clutter (improved to 0.42)
    2.5,   # Flowers ← BOOSTED from 1.20 to 2.5
    1.8,   # Logs (improved to 0.31)
    1.5,   # Rocks (improved to 0.50)
    0.5,   # Landscape (good at 0.66)
    0.4,   # Sky (excellent at 0.94)
], dtype=torch.float32)

# Normalize
class_weights = class_weights / class_weights.sum() * Config.NUM_CLASSES

print(f"\n{'='*70}")
print("OPTIMIZED CLASS WEIGHTS (BOOSTED DRY BUSHES & FLOWERS)")
print(f"{'='*70}")
for i, (name, weight) in enumerate(zip(Config.CLASS_NAMES, class_weights)):
    pixel_pct = (train_dist.get(i, 0) / total_pixels * 100)
    marker = "🔥" if weight > 2.0 else "✓"
    print(f"{marker} {name:15s}: {weight:.4f} (pixel%: {pixel_pct:5.2f}%)")

print(f"\n✓ Dry Bushes weight: {class_weights[3]:.2f} (was 1.59, now 3.0)")
print(f"✓ Flowers weight: {class_weights[5]:.2f} (was 1.20, now 2.5)")
print("=" * 70)

# Create weighted sampler to oversample images with Dry Bushes & Flowers
from torch.utils.data import WeightedRandomSampler

def create_weighted_sampler(mask_dir):
    """Give 3x weight to images containing Dry Bushes or Flowers"""
    mask_paths = sorted(list(Path(mask_dir).glob("*.png")))
    if len(mask_paths) == 0:
        mask_paths = sorted(list(Path(mask_dir).glob("*.jpg")))

    sample_weights = []
    dry_bushes_count = 0
    flowers_count = 0

    print("Analyzing images for weighted sampling...")
    for mask_path in tqdm(mask_paths):
        mask = cv2.imread(str(mask_path), cv2.IMREAD_UNCHANGED)

        # Check if contains target classes
        has_dry_bushes = (mask == 500).any()  # Dry Bushes
        has_flowers = (mask == 600).any()      # Flowers

        if has_dry_bushes or has_flowers:
            sample_weights.append(3.0)  # 3x weight
            if has_dry_bushes:
                dry_bushes_count += 1
            if has_flowers:
                flowers_count += 1
        else:
            sample_weights.append(1.0)  # Normal weight

    print(f"\n📊 Weighted Sampling Stats:")
    print(f"   Images with Dry Bushes: {dry_bushes_count}/{len(mask_paths)} ({dry_bushes_count/len(mask_paths)*100:.1f}%)")
    print(f"   Images with Flowers: {flowers_count}/{len(mask_paths)} ({flowers_count/len(mask_paths)*100:.1f}%)")
    print(f"   Boosted images will appear 3x more often during training")

    return WeightedRandomSampler(
        weights=sample_weights,
        num_samples=len(sample_weights),
        replacement=True
    )

# Create sampler
train_sampler = create_weighted_sampler(Config.TRAIN_MASK_DIR)
print("✓ Weighted sampler created\n")

# Create datasets
train_dataset = DesertSegmentationDataset(
    Config.TRAIN_IMG_DIR,
    Config.TRAIN_MASK_DIR,
    transform=get_training_augmentation()
)

val_dataset = DesertSegmentationDataset(
    Config.VAL_IMG_DIR,
    Config.VAL_MASK_DIR,
    transform=get_validation_augmentation()
)

# Create dataloaders
train_loader = DataLoader(
    train_dataset,
    batch_size=Config.BATCH_SIZE,
    sampler=train_sampler,
    num_workers=Config.NUM_WORKERS,
    pin_memory=True,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=Config.BATCH_SIZE,
    shuffle=False,
    num_workers=Config.NUM_WORKERS,
    pin_memory=True,
)

print("=" * 70)
print("Dataloaders created with WEIGHTED SAMPLING")
print(f"Train batches: {len(train_loader)}")
print(f"Val batches: {len(val_loader)}")
print("=" * 70)

def calculate_iou(pred, target, num_classes=Config.NUM_CLASSES):
    """Calculate IoU for segmentation"""
    ious = []
    pred = pred.view(-1).cpu().numpy()
    target = target.view(-1).cpu().numpy()

    for cls in range(num_classes):
        pred_inds = pred == cls
        target_inds = target == cls
        intersection = (pred_inds & target_inds).sum()
        union = (pred_inds | target_inds).sum()

        if union == 0:
            ious.append(float('nan'))
        else:
            ious.append(intersection / union)

    # Mean IoU (ignoring NaN values)
    valid_ious = [iou for iou in ious if not np.isnan(iou)]
    mean_iou = np.mean(valid_ious) if valid_ious else 0.0

    return mean_iou, np.array(ious)

def calculate_pixel_accuracy(pred, target):
    """Calculate pixel-wise accuracy"""
    correct = (pred == target).sum().item()
    total = target.numel()
    return correct / total

print("Metrics functions defined")

class CombinedLoss(nn.Module):
    """Combination of Dice Loss and CrossEntropy with class weights"""
    def __init__(self, class_weights=None, dice_weight=0.5, ce_weight=0.5):
        super().__init__()
        self.dice_weight = dice_weight
        self.ce_weight = ce_weight
        self.class_weights = class_weights

        # CrossEntropy with class weights
        if class_weights is not None:
            self.ce = nn.CrossEntropyLoss(weight=class_weights)
        else:
            self.ce = nn.CrossEntropyLoss()

    def dice_loss(self, pred, target, smooth=1e-6):
        """Soft Dice Loss"""
        pred = torch.softmax(pred, dim=1)
        target_one_hot = torch.zeros_like(pred)
        target_one_hot.scatter_(1, target.unsqueeze(1), 1)

        intersection = (pred * target_one_hot).sum(dim=(2, 3))
        union = pred.sum(dim=(2, 3)) + target_one_hot.sum(dim=(2, 3))

        dice_score = (2. * intersection + smooth) / (union + smooth)
        return 1 - dice_score.mean()

    def forward(self, pred, target):
        dice = self.dice_loss(pred, target)
        ce = self.ce(pred, target)
        return self.dice_weight * dice + self.ce_weight * ce

print("Loss function defined")

import zipfile
from datetime import datetime
from pathlib import Path

def create_backup_zip(epoch, include_all=False):
    """Create a downloadable ZIP backup of checkpoints and outputs"""
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

    if include_all:
        # Full backup - everything
        zip_filename = f"/kaggle/working/full_backup_{Config.RUN_NAME}_ep{epoch+1}_{timestamp}.zip"
        print(f"\n{'='*70}")
        print("Creating FULL BACKUP ZIP...")
        print(f"{'='*70}")
    else:
        # Quick backup - just best model and latest checkpoint
        zip_filename = f"/kaggle/working/quick_backup_{Config.RUN_NAME}_ep{epoch+1}.zip"
        print(f"\nCreating quick backup ZIP...")

    with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Always include best model
        best_model_path = Path(Config.CHECKPOINT_DIR) / "best_model.pth"
        if best_model_path.exists():
            zipf.write(best_model_path, arcname=f"checkpoints/best_model.pth")
            print(f"  ✓ Added: best_model.pth")

        if include_all:
            # Add all checkpoints
            for ckpt_file in Path(Config.CHECKPOINT_DIR).glob("checkpoint_epoch_*.pth"):
                zipf.write(ckpt_file, arcname=f"checkpoints/{ckpt_file.name}")
                print(f"  ✓ Added: {ckpt_file.name}")

            # Add training history JSON if exists
            history_path = Path(Config.OUTPUT_DIR) / "training_history.json"
            if history_path.exists():
                zipf.write(history_path, arcname="training_history.json")
                print(f"  ✓ Added: training_history.json")

            # Add training curves image if exists
            for img_file in Path(Config.OUTPUT_DIR).glob("*.png"):
                zipf.write(img_file, arcname=f"outputs/{img_file.name}")
                print(f"  ✓ Added: {img_file.name}")

            # Add any other output files
            for output_file in Path(Config.OUTPUT_DIR).glob("*.txt"):
                zipf.write(output_file, arcname=f"outputs/{output_file.name}")
                print(f"  ✓ Added: {output_file.name}")
        else:
            # Quick backup - just latest checkpoint
            latest_ckpt = Path(Config.CHECKPOINT_DIR) / f"checkpoint_epoch_{epoch+1}.pth"
            if latest_ckpt.exists():
                zipf.write(latest_ckpt, arcname=f"checkpoints/{latest_ckpt.name}")
                print(f"  ✓ Added: {latest_ckpt.name}")

    zip_size_mb = Path(zip_filename).stat().st_size / (1024 * 1024)
    print(f"{'='*70}")
    print(f"✓ ZIP created: {Path(zip_filename).name}")
    print(f"✓ Size: {zip_size_mb:.2f} MB")
    print(f"✓ Location: /kaggle/working/")
    print(f"{'='*70}\n")

    return zip_filename


def save_checkpoint(epoch, model, optimizer, scheduler, scaler, metrics, is_best):
    """Save checkpoint locally AND create ZIP backup with auto-cleanup"""
    # Extract model if DataParallel
    model_state = model.module.state_dict() if isinstance(model, nn.DataParallel) else model.state_dict()

    checkpoint = {
        'epoch': epoch,
        'model_state_dict': model_state,
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'scaler_state_dict': scaler.state_dict(),
        'metrics': metrics,
        'config': {
            'encoder': Config.ENCODER,
            'num_classes': Config.NUM_CLASSES,
            'img_size': (Config.IMG_HEIGHT, Config.IMG_WIDTH),
            'run_name': Config.RUN_NAME,
        }
    }

    # Save local checkpoint
    checkpoint_path = Path(Config.CHECKPOINT_DIR) / f"checkpoint_epoch_{epoch+1}.pth"
    torch.save(checkpoint, checkpoint_path)
    print(f"✓ Saved: {checkpoint_path.name}")

    # Save best model
    if is_best:
        best_path = Path(Config.CHECKPOINT_DIR) / "best_model.pth"
        torch.save(checkpoint, best_path)
        print(f"✓ BEST MODEL! Val IoU: {metrics.get('val_iou', 0):.4f}")

        # Create quick ZIP backup when best model is saved
        create_backup_zip(epoch, include_all=False)

        # Clean up old quick backups (keep only last 2)
        quick_backups = sorted(Path("/kaggle/working").glob("quick_backup_*.zip"))
        if len(quick_backups) > 2:
            for old_zip in quick_backups[:-2]:
                old_size_mb = old_zip.stat().st_size / (1024 * 1024)
                old_zip.unlink()
                print(f"  🗑️  Deleted old quick backup: {old_zip.name} ({old_size_mb:.1f} MB freed)")

    # Create full backup every N epochs
    if (epoch + 1) % Config.BACKUP_FREQUENCY == 0:
        create_backup_zip(epoch, include_all=True)

        # Clean up old full backups (keep only last 2)
        full_backups = sorted(Path("/kaggle/working").glob("full_backup_*.zip"))
        if len(full_backups) > 2:
            for old_zip in full_backups[:-2]:
                old_size_mb = old_zip.stat().st_size / (1024 * 1024)
                old_zip.unlink()
                print(f"  🗑️  Deleted old full backup: {old_zip.name} ({old_size_mb:.1f} MB freed)")

    # Keep only last N checkpoints locally (save space)
    checkpoints = sorted(Path(Config.CHECKPOINT_DIR).glob("checkpoint_epoch_*.pth"))
    if len(checkpoints) > Config.KEEP_LAST_N_CHECKPOINTS:
        for old_checkpoint in checkpoints[:-Config.KEEP_LAST_N_CHECKPOINTS]:
            old_checkpoint.unlink()


def load_checkpoint(checkpoint_path, model, optimizer, scheduler, scaler):
    """Load checkpoint"""
    checkpoint = torch.load(checkpoint_path)

    # Load into module if DataParallel
    if isinstance(model, nn.DataParallel):
        model.module.load_state_dict(checkpoint['model_state_dict'])
    else:
        model.load_state_dict(checkpoint['model_state_dict'])

    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
    scaler.load_state_dict(checkpoint['scaler_state_dict'])

    return checkpoint['epoch'], checkpoint['metrics']


print("✓ Checkpoint functions defined (with ZIP backup + auto-cleanup)")

def train_epoch(model, dataloader, criterion, optimizer, scheduler, scaler, device, epoch):
    """Train for one epoch with mixed precision"""
    model.train()
    running_loss = 0.0
    running_iou = 0.0
    running_acc = 0.0

    pbar = tqdm(dataloader, desc=f"Epoch {epoch} Train")
    for batch_idx, (images, masks) in enumerate(pbar):
        images = images.to(device, non_blocking=True)
        masks = masks.to(device, non_blocking=True)

        optimizer.zero_grad()

        # Mixed precision forward
        with torch.cuda.amp.autocast(enabled=Config.USE_AMP):
            outputs = model(images)
            loss = criterion(outputs, masks)

        # Mixed precision backward
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        # Step scheduler every batch for OneCycleLR
        scheduler.step()

        # Metrics (outside autocast)
        with torch.no_grad():
            preds = torch.argmax(outputs, dim=1)
            batch_iou, _ = calculate_iou(preds, masks)
            batch_acc = calculate_pixel_accuracy(preds, masks)

        running_loss += loss.item()
        running_iou += batch_iou
        running_acc += batch_acc

        pbar.set_postfix({
            'loss': f'{loss.item():.4f}',
            'iou': f'{batch_iou:.4f}',
            'acc': f'{batch_acc:.4f}',
            'lr': f'{optimizer.param_groups[0]["lr"]:.2e}'
        })

        # Log to WandB periodically
        if Config.USE_WANDB and batch_idx % 50 == 0:
            wandb.log({
                'batch_train_loss': loss.item(),
                'batch_train_iou': batch_iou,
                'batch_train_acc': batch_acc,
                'learning_rate': optimizer.param_groups[0]['lr'],
            })

    epoch_loss = running_loss / len(dataloader)
    epoch_iou = running_iou / len(dataloader)
    epoch_acc = running_acc / len(dataloader)

    return epoch_loss, epoch_iou, epoch_acc

def validate_epoch(model, dataloader, criterion, device, epoch):
    """Validation with mixed precision"""
    model.eval()
    running_loss = 0.0
    running_iou = 0.0
    running_acc = 0.0
    class_iou_sum = np.zeros(Config.NUM_CLASSES)

    with torch.no_grad():
        pbar = tqdm(dataloader, desc=f"Epoch {epoch} Val")
        for images, masks in pbar:
            images = images.to(device, non_blocking=True)
            masks = masks.to(device, non_blocking=True)

            # Mixed precision inference
            with torch.cuda.amp.autocast(enabled=Config.USE_AMP):
                outputs = model(images)
                loss = criterion(outputs, masks)

            preds = torch.argmax(outputs, dim=1)
            batch_iou, class_ious = calculate_iou(preds, masks)
            batch_acc = calculate_pixel_accuracy(preds, masks)

            running_loss += loss.item()
            running_iou += batch_iou
            running_acc += batch_acc

            # Handle NaN in class IoUs
            class_ious = np.nan_to_num(class_ious, nan=0.0)
            class_iou_sum += class_ious

            pbar.set_postfix({
                'loss': f'{loss.item():.4f}',
                'iou': f'{batch_iou:.4f}',
                'acc': f'{batch_acc:.4f}'
            })

    epoch_loss = running_loss / len(dataloader)
    epoch_iou = running_iou / len(dataloader)
    epoch_acc = running_acc / len(dataloader)
    class_ious = class_iou_sum / len(dataloader)

    return epoch_loss, epoch_iou, epoch_acc, class_ious

print("Training functions defined")

class EarlyStopping:
    """Early stopping with patience"""
    def __init__(self, patience=20, min_delta=0.001):  # Increased patience
        self.patience = patience
        self.min_delta = min_delta
        self.counter = 0
        self.best_score = None
        self.early_stop = False

    def __call__(self, val_metric):
        score = val_metric

        if self.best_score is None:
            self.best_score = score
        elif score < self.best_score + self.min_delta:
            self.counter += 1
            print(f"EarlyStopping counter: {self.counter}/{self.patience}")
            if self.counter >= self.patience:
                self.early_stop = True
        else:
            self.best_score = score
            self.counter = 0

        return self.early_stop

early_stopping = EarlyStopping(
    patience=20,  # Increased from 15
    min_delta=0.001
)

print("Early stopping initialized (patience=20)")

print("=" * 70)
print("INITIALIZING MODEL AND TRAINING COMPONENTS")
print("=" * 70)

# Create model
model = smp.Unet(
    encoder_name=Config.ENCODER,
    encoder_weights=Config.ENCODER_WEIGHTS,
    in_channels=3,
    classes=Config.NUM_CLASSES,
    activation=Config.ACTIVATION,
)

print(f"Model created: {Config.ENCODER}")
print(f"Total parameters: {sum(p.numel() for p in model.parameters()):,}")

# Multi-GPU wrapper
if Config.USE_MULTI_GPU and torch.cuda.device_count() > 1:
    print(f"Using {torch.cuda.device_count()} GPUs with DataParallel")
    model = nn.DataParallel(model)
else:
    print("Using single GPU")

model = model.to(Config.DEVICE)

# Loss with HIGHER DICE WEIGHT for better IoU
criterion = CombinedLoss(
    class_weights=class_weights.to(Config.DEVICE),
    dice_weight=0.75,  # Increased from 0.7 → 0.75
    ce_weight=0.25     # Decreased from 0.3 → 0.25
)
print("Loss: 0.75*Dice + 0.25*CrossEntropy (boosted Dry Bushes & Flowers)")

# Optimizer
optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=Config.LEARNING_RATE,
    weight_decay=Config.WEIGHT_DECAY,
    betas=(0.9, 0.999),
)
print(f"Optimizer: AdamW (lr={Config.LEARNING_RATE}, wd={Config.WEIGHT_DECAY})")

# Scheduler
steps_per_epoch = len(train_loader)
scheduler = torch.optim.lr_scheduler.OneCycleLR(
    optimizer,
    max_lr=Config.LEARNING_RATE,
    epochs=Config.NUM_EPOCHS,
    steps_per_epoch=steps_per_epoch,
    pct_start=0.2,
    anneal_strategy='cos',
    div_factor=10.0,
    final_div_factor=1e3,
)
print(f"Scheduler: OneCycleLR (peak at epoch ~{int(Config.NUM_EPOCHS*0.2)})")

# Mixed precision scaler
scaler = torch.cuda.amp.GradScaler(enabled=Config.USE_AMP)
print(f"Mixed Precision: {'Enabled' if Config.USE_AMP else 'Disabled'}")

# Training state
start_epoch = 0
best_iou = 0.0
history = {
    'train_loss': [],
    'train_iou': [],
    'train_acc': [],
    'val_loss': [],
    'val_iou': [],
    'val_acc': [],
    'class_ious': [],
}

print("=" * 70)
print("OPTIMIZATIONS FOR DRY BUSHES & FLOWERS:")
print("=" * 70)
print("✓ Class weights: Dry Bushes 3.0, Flowers 2.5")
print("✓ Weighted sampling: 3x oversampling of target classes")
print("✓ Dice weight: 0.75 (higher IoU focus)")
print("✓ Drive backup: Every 5 epochs + best model")
print("=" * 70)

# Run all cells in order, then this training loop:
print("=" * 70)
print("STARTING TRAINING WITH AUTO-CLEANUP")
print("=" * 70)

for epoch in range(start_epoch, Config.NUM_EPOCHS):
    print(f"\nEpoch {epoch+1}/{Config.NUM_EPOCHS}")
    print("-" * 70)

    # Train
    train_loss, train_iou, train_acc = train_epoch(
        model, train_loader, criterion, optimizer, scheduler, scaler, Config.DEVICE, epoch+1
    )

    # Validate
    val_loss, val_iou, val_acc, class_ious = validate_epoch(
        model, val_loader, criterion, Config.DEVICE, epoch+1
    )

    current_lr = optimizer.param_groups[0]['lr']

    # Save history
    history['train_loss'].append(train_loss)
    history['train_iou'].append(train_iou)
    history['train_acc'].append(train_acc)
    history['val_loss'].append(val_loss)
    history['val_iou'].append(val_iou)
    history['val_acc'].append(val_acc)
    history['class_ious'].append(class_ious.tolist())

    # Print summary
    print("-" * 70)
    print(f"Epoch {epoch+1} Summary:")
    print("-" * 70)
    print(f"Train - Loss: {train_loss:.4f} | IoU: {train_iou:.4f} | Acc: {train_acc:.4f}")
    print(f"Val   - Loss: {val_loss:.4f} | IoU: {val_iou:.4f} | Acc: {val_acc:.4f}")
    print(f"LR: {current_lr:.6f}")
    print(f"\nPer-Class IoU:")
    for name, iou in zip(Config.CLASS_NAMES, class_ious):
        print(f"  {name:15s}: {iou:.4f}")
    print("-" * 70)

    # Log to WandB
    if Config.USE_WANDB:
        log_dict = {
            'epoch': epoch + 1,
            'train_loss': train_loss,
            'train_iou': train_iou,
            'train_acc': train_acc,
            'val_loss': val_loss,
            'val_iou': val_iou,
            'val_acc': val_acc,
            'learning_rate': current_lr,
        }
        for name, iou in zip(Config.CLASS_NAMES, class_ious):
            log_dict[f'class_iou/{name}'] = iou
        wandb.log(log_dict)

    # Check if best
    is_best = val_iou > best_iou
    if is_best:
        best_iou = val_iou
        print(f"🏆 New best IoU: {best_iou:.4f}")

    metrics = {
        'train_loss': train_loss,
        'train_iou': train_iou,
        'train_acc': train_acc,
        'val_loss': val_loss,
        'val_iou': val_iou,
        'val_acc': val_acc,
        'class_ious': class_ious.tolist(),
    }

    # Save checkpoint (happens every SAVE_FREQUENCY or when best)
    if (epoch + 1) % Config.SAVE_FREQUENCY == 0 or is_best:
        save_checkpoint(epoch, model, optimizer, scheduler, scaler, metrics, is_best)

    # Early stopping
    if early_stopping(val_iou):
        print(f"\n⚠️  Training stopped early at epoch {epoch+1}")
        save_checkpoint(epoch, model, optimizer, scheduler, scaler, metrics, is_best=False)
        break

print("=" * 70)
print("🎉 TRAINING COMPLETE")
print(f"Best Val IoU: {best_iou:.4f}")
print("=" * 70)

# Save final history
history_path = Path(Config.OUTPUT_DIR) / "training_history.json"
with open(history_path, 'w') as f:
    json.dump(history, f, indent=2)
print(f"Training history saved to: {history_path}")

if Config.USE_WANDB:
    wandb.finish()

# Plot training curves
fig, axes = plt.subplots(2, 2, figsize=(15, 10))

# Loss
axes[0, 0].plot(history['train_loss'], label='Train Loss')
axes[0, 0].plot(history['val_loss'], label='Val Loss')
axes[0, 0].set_xlabel('Epoch')
axes[0, 0].set_ylabel('Loss')
axes[0, 0].set_title('Training and Validation Loss')
axes[0, 0].legend()
axes[0, 0].grid(True)

# IoU
axes[0, 1].plot(history['train_iou'], label='Train IoU')
axes[0, 1].plot(history['val_iou'], label='Val IoU')
axes[0, 1].set_xlabel('Epoch')
axes[0, 1].set_ylabel('IoU')
axes[0, 1].set_title('Training and Validation IoU')
axes[0, 1].legend()
axes[0, 1].grid(True)

# Accuracy
axes[1, 0].plot(history['train_acc'], label='Train Acc')
axes[1, 0].plot(history['val_acc'], label='Val Acc')
axes[1, 0].set_xlabel('Epoch')
axes[1, 0].set_ylabel('Accuracy')
axes[1, 0].set_title('Training and Validation Accuracy')
axes[1, 0].legend()
axes[1, 0].grid(True)

# Per-class IoU (last epoch)
if len(history['class_ious']) > 0:
    last_class_ious = history['class_ious'][-1]
    axes[1, 1].bar(range(len(Config.CLASS_NAMES)), last_class_ious)
    axes[1, 1].set_xticks(range(len(Config.CLASS_NAMES)))
    axes[1, 1].set_xticklabels(Config.CLASS_NAMES, rotation=45, ha='right')
    axes[1, 1].set_ylabel('IoU')
    axes[1, 1].set_title('Final Per-Class IoU')
    axes[1, 1].grid(True, axis='y')

plt.tight_layout()
plt.savefig(Path(Config.OUTPUT_DIR) / 'training_curves.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"Training curves saved to: {Config.OUTPUT_DIR}/training_curves.png")

# After training completes - create final comprehensive backup

print("\n" + "="*70)
print("CREATING FINAL BACKUP ZIP")
print("="*70)

# Save training history
history_path = Path(Config.OUTPUT_DIR) / "training_history.json"
with open(history_path, 'w') as f:
    json.dump(history, f, indent=2)
print(f"✓ Saved: training_history.json")

# Create final summary
summary_path = Path(Config.OUTPUT_DIR) / "training_summary.txt"
with open(summary_path, 'w') as f:
    f.write(f"Training Summary - {Config.RUN_NAME}\n")
    f.write("=" * 70 + "\n\n")
    f.write(f"Best Val IoU: {best_iou:.4f}\n")
    f.write(f"Best Val Acc: {max(history['val_acc']):.4f}\n")
    f.write(f"Total Epochs: {len(history['val_iou'])}\n")
    f.write(f"Final Epoch: {len(history['val_iou'])}\n\n")
    f.write("Final Per-Class IoU:\n")
    if history['class_ious']:
        for name, iou in zip(Config.CLASS_NAMES, history['class_ious'][-1]):
            f.write(f"  {name:15s}: {iou:.4f}\n")
print(f"✓ Saved: training_summary.txt")

# Create FINAL comprehensive ZIP
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
final_zip = f"/kaggle/working/FINAL_BACKUP_{Config.RUN_NAME}_{timestamp}.zip"

print(f"\nCreating comprehensive final backup...")
with zipfile.ZipFile(final_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
    # Best model
    best_model_path = Path(Config.CHECKPOINT_DIR) / "best_model.pth"
    if best_model_path.exists():
        zipf.write(best_model_path, arcname="best_model.pth")
        print(f"  ✓ Added: best_model.pth")

    # All checkpoints
    for ckpt_file in sorted(Path(Config.CHECKPOINT_DIR).glob("*.pth")):
        zipf.write(ckpt_file, arcname=f"checkpoints/{ckpt_file.name}")
        print(f"  ✓ Added: {ckpt_file.name}")

    # Training history
    zipf.write(history_path, arcname="training_history.json")
    print(f"  ✓ Added: training_history.json")

    # Summary
    zipf.write(summary_path, arcname="training_summary.txt")
    print(f"  ✓ Added: training_summary.txt")

    # All plots and outputs
    for output_file in Path(Config.OUTPUT_DIR).glob("*"):
        if output_file.is_file():
            zipf.write(output_file, arcname=f"outputs/{output_file.name}")
            print(f"  ✓ Added: {output_file.name}")

final_size_mb = Path(final_zip).stat().st_size / (1024 * 1024)

print("\n" + "="*70)
print("🎉 FINAL BACKUP COMPLETE!")
print("="*70)
print(f"📦 File: {Path(final_zip).name}")
print(f"📊 Size: {final_size_mb:.2f} MB")
print(f"📁 Location: /kaggle/working/")
print("\n💾 Download this file from Kaggle Output section")
print("="*70)

!zip -r training_output.zip outputs

from IPython.display import FileLink
FileLink("/kaggle/working/training_output.zip")

